### ISSUE TITLE
Concentric Circles

### ISSUE THREAD

**Issue by sujatroy** [grvashu/srishti-digital-interfaces#13]
Unable to stop the loop for concentric circle(only 10).

code:-

var a=20
function setup(){
	createCanvas(600, 600);
}

function draw() 
{
 noFill();
 stroke(100);   
    a = a + 10;
ellipse(300, 300, a, a);
}

**Comment by grvashu** [comment]
Add a boundary condition.

Let's say you want to stop the execution when a reaches 100. You can write like this.

```javascript
if(a<100)
{
    ellipse(300,300,a,a);
}
a=a+10;
```

Make sense?
