### ISSUE TITLE
Unable to upload any files or folders.

### ISSUE THREAD

**Issue by cezriel** [grvashu/srishti-digital-interfaces#16]
![err](https://cloud.githubusercontent.com/assets/20962243/18209623/2d18b68a-7152-11e6-96d1-26d627acd014.png)

**Comment by grvashu** [comment]
This typically happens when the folder is empty or the file inside the folder is empty. Recheck your files - they shouldn't be empty. 

If you are still not able to upload them. Send me your files (with your name) at gaurav.singh[at]srishti.ac.in.
