### ISSUE TITLE
linking files

### ISSUE THREAD

**Issue by im-yashjain** [grvashu/srishti-digital-interfaces#17]
hay gaurav
my issue of linking html files to each other is still the same.
im not able to like any html file from a js file 
how do i do this?
can you send me an example ?

**Comment by grvashu** [comment]
I'm not sure what you intend to do.
Do you want to manipulate HTML elements from sketch.js?

By the way, some of your latest uploads do not have `<body>` in the HTML files.

**Comment by shraddharastogi** [comment]
I can link the html with my js file. But, i don't know how to get it to the position i desire. How to do that?

**Comment by grvashu** [comment]
Check this.

```javascript
var canvas;
function setup() {
  canvas = createCanvas(400,400);
  canvas.position(100,100);
  canvas.background(0);
}
```

**Comment by shraddharastogi** [comment]
Nope. This isn't working either.

**Comment by grvashu** [comment]
Zip your files and attach in the comment below.
I will have a look.

**Comment by shraddharastogi** [comment]
i can't it say we don't support Zip files

**Comment by grvashu** [comment]
Check this zip. Extract and run the HTML file in your browser.
[positionDemo.zip](https://github.com/grvashu/srishti-digital-interfaces/files/453887/positionDemo.zip)

Do you see custom position of the canvas here?

**Comment by shraddharastogi** [comment]
Yes. I do.

**Comment by grvashu** [comment]
Compare your code with mine.
Is your query resolved now?

**Comment by Anavi6** [comment]
Shraddha try this-
in your .js file just write-

`function setup()
{
canvas=createCanvas(windowWidth, 200);
    canvas.class("canvashome");`
}


in your css file write
`.canvashome{
    position: absolute;
    left: 0px;
    top: 0px;
`

**Comment by shraddharastogi** [comment]
Anavi, This didn't work either. Thanks a lot though. :)
