### ISSUE TITLE
My folder in getting uploaded in the "Anavi%20Dhawan/A3 Portfolio site"

### ISSUE THREAD

**Issue by Anavi6** [grvashu/srishti-digital-interfaces#18]
I don't know how to change this and put it in my folder named "Anavi Dhawan"

**Comment by RebeccaMathew** [comment]
I have uploaded my work 2 days ago as A3 - PORTFOLIO in my folder. Now, that is outside my folder. Should I reupload it?

**Comment by grvashu** [comment]
I have put your A3 folders into your designated folders.
Thanks and you don't need to change/upload anything.
