### ISSUE TITLE
done with work!

### ISSUE THREAD

**Issue by im-yashjain** [grvashu/srishti-digital-interfaces#3]
im done with my first 2 weeks's work

can you let me know if there is anything else i could work on

**Comment by grvashu** [comment]
Great. 

Here are few things that you may try out.
1. Simulate Newton's cradle
2. Week 2 Assignment in a 3D box?
3. Simulate Spirograph drawings

**Comment by grvashu** [comment]
@im-yashjain Checked your programs. All good.
You have missed Week 2 assignment.

**Comment by im-yashjain** [comment]
Hay gaurav

I have uploaded all the 6 assigned classwork for the 2nd week already.
Please check and update

**Comment by grvashu** [comment]
There is also an assignment in week 2 apart from the classwork.
See https://github.com/grvashu/srishti-digital-interfaces/wiki/Week-2
