### ISSUE TITLE
I've uploaded a processing code for writing calligraphy. There is one problem with it though.

### ISSUE THREAD

**Issue by Anavi6** [grvashu/srishti-digital-interfaces#5]
When you click the mouse, ive programmed the mouse to change to a big white line to act as the eraser. The problem with doing that is that after finishing one letter, it makes it hard to shift to another letter because when i click the mouse, part of the letter gets eraser. If I don't click, the pen tool(slanted black line) keeps making marks on the page. Is there any way that I can create a button when I want to switch to eraser to solve this problem?

**Comment by grvashu** [comment]
Check this example to see how you can have buttons and p5.js work together.
[](https://p5js.org/examples/examples/Dom_Input_and_Button.php)

I will anyways introduce P5.js interactivity with DOM elements in 4th week.

**Comment by Anavi6** [comment]
Which example?

**Comment by grvashu** [comment]
Sorry, missed the link above.

Here it is: https://p5js.org/examples/examples/Dom_Input_and_Button.php
