### ISSUE TITLE
How to add fonts other than "CSS Web Safe Fonts"?

### ISSUE THREAD

**Issue by RebeccaMathew** [grvashu/srishti-digital-interfaces#6]
I have notice other websites having fancy fonts which i'm not able to do that. I do not want to use web safe fonts. Is there any way in doing so. Or do i have make them and convert into img?

**Comment by grvashu** [comment]
Here you go!

```html
<!DOCTYPE html>
<html>
    <head>
        <style>
            @font-face {
                font-family: myFont;
                src: url(AlexBrush-Regular.ttf);
            }

            h1 {
                font-family: myFont;
            }
        </style>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>
```

Step 1: Create a font face with a desired font-family name and source url.
Step 2: You can now use the font-family name that you created anywhere in your html page without single quotes.

Hope this helps.

**Comment by RebeccaMathew** [comment]
Thank you but i still didn't understand the source url part.

**Comment by grvashu** [comment]
Source URL is the path address to the font file. If the font file is in the same folder as HTML file, the source URL will be just the font file name (with its extension).

Make sense?

**Comment by radhapennathur** [comment]
I've tried this but it still doesn't seem to work. :/ 

<html>
<head>
  <style>
    
    @font-face {
      font-family:Fox & Cat;
      src: url(Fox & Cat.ttf);
      
    }
  
    h1
    { 
      color: slategrey;
      text-align:center;
      padding: 20px;
      margin: 30px;
      font-family:Fox & Cat;
      font-size: 40px;
    }
  
  </style>
  </head>
  
  <body>
    <h1> Portfolio </h1>

</body>
</html>


The font file is in the same folder as well.

**Comment by grvashu** [comment]
@RebeccaMathew Let me know if you able to get it working?

**Comment by RebeccaMathew** [comment]
No it's not. 😞

**Comment by grvashu** [comment]
Please share your code.

**Comment by RebeccaMathew** [comment]
@font-face{
    font-family: myFont;
    src: url(Flamenco-Regular.otf);
}

header{
   font-family: myFont;
    font-size: 80px;
    font-style: normal;
    position:absolute;
    top:15px;
    left: 615px;
    text-align: center;
    background-color: black;
    color: white;
    padding:5px;
 
}

**Comment by grvashu** [comment]
Your code looks fine. The issue to appears to be most likely with the directory structure.

Download [font-example.zip](https://github.com/grvashu/srishti-digital-interfaces/files/420279/font-example.zip) and see if this is working fine at your end.

**Comment by RebeccaMathew** [comment]
Its still not working

**Comment by grvashu** [comment]
I'm not sure what is the issue. I will have a look at this in the next class.
