### ISSUE TITLE
Generating random numbers

### ISSUE THREAD

**Issue by im-yashjain** [grvashu/srishti-digital-interfaces#7]
what is the command for getting random numbers and how do i use it.
is there any formula?
also i have uploaded the assignment and have managed to make the ball bounce using a very simple code
but its too simple. the ball is bouncing in the same pattern .
can you please help me with that

**Comment by grvashu** [comment]
See [random()](https://p5js.org/reference/#/p5/random ) function for generating random numbers.

To avoid the ball to move in the same pattern, try changing its initial position to anything other than (0,0) and also make sure that the speed in x-axis and y-axis is not same.
