### ISSUE TITLE
bouncing ball command

### ISSUE THREAD

**Issue by shraddharastogi** [grvashu/srishti-digital-interfaces#9]
my code for bouncing ball isn't working and i also couldn't figure how to use the loop for making a diagonal line. I tried the grid too. The code doesn't work.

**Comment by grvashu** [comment]
Please share specific part of your code where you are facing problem.

**Comment by shraddharastogi** [comment]
So, I took some help. this issue has gotten resolved. 
But, for the 10x10 grid. I looked up this video where he made a grid. 
i tried using the same code. It doesn't work. 
var x=0,var y=0;
this all comes under function draw(){
 x=50;
    while(x<width){
        line(x,o,x,height);
        x=x+50;
    }
   y=50
    while(y<height){
        line(0,y,width,y);
        y=y+50;}
}

**Comment by grvashu** [comment]
First thing, always define your canvas size in the setup function. Second thing, the function call for the `line()` has 'o' instead of 0.

**Comment by shraddharastogi** [comment]
canvas size was in setup function only.  Also, changed the function call for line(). Code is still not working.

**Comment by grvashu** [comment]
Please zip all three files (p5.js, sketch.js and index.html) and attach as a comment here. I will have a look.
